export const TYPES = ['programming', 'robotics'];

export const projects = [
    {
        year: 2025,
        type: 'programming',
        title: 'This Website',
        desc: 'A playground using Sveltekit and daisyUI.',
        image: 'website1.png',
        mdsvex: 'myWebsite',
        icons: ['svelte', 'js', 'tailwindcss', 'daisyui'],
    },
    {
        year: 2025,
        type: 'robotics',
        title: 'VEX Robotics',
        desc: 'Programmed Swerve Drive from complete scratch.',
        image: 'vex2.jpg',
        mdsvex: 'vex',
        icons: ['c++'],
    },
    {
        year: 2024,
        type: 'robotics',
        title: 'FTC Robotics',
        desc: 'Programmed a 3 dof robotic arm.',
        image: 'ftc3.png',
        mdsvex: 'ftc',
        icons: ['java'],
    },
    {
        year: 2024,
        type: 'programming',
        title: 'Dental AI App',
        desc: 'Mobile app made with Flutter diagnosing using a Teachable Machine model with Firebase G-login and database.',
        image: 'dentalapp1.png',
        mdsvex: 'dentalapp',
        icons: ['flutter', 'firebase', 'dart'],
    },
    {
        year: 2024,
        type: 'programming',
        title: 'AI Resaurant Recommender',
        desc: 'Hackathon project that based on your location and preferences, rates and recommends surrounding restaurants. It uses Google Places API, Yelp API, OpenAI API, and Firebase.',
        image: 'airesturant1.png',
        mdsvex: 'airesturant',
        icons: ['flutter', 'firebase', 'dart'],
    },
    {
        year: 2024,
        type: 'programming',
        title: 'Course Guide',
        desc: 'I parsed my school\'s course guide PDF into an interactive web app, using flutter and firebase. It has access levels, allowing CRUD.',
        image: 'courseGuide1.png',
        mdsvex: 'courseGuide',
        icons: ['flutter', 'firebase', 'dart'],
    },
    {
        year: 2024,
        type: 'programming',
        title: 'Naive Bayes Spam Email Detection',
        desc: 'Psuedo-Machine Learning from scratch, detecting spam emails with just a small set of data.',
        image: 'naivebayes1.png',
        mdsvex: 'naiveBayes',
        icons: ['py'],
    },
    {
        year: 2023,
        type: 'robotics',
        title: 'Arduino Airplane and Transmitter',
        desc: 'Airplane COMPLETELY FROM SCRATCH. Including custom arduino transmitter, arduino flight controller, and a handmade plane.',
        image: 'plane/old_plane_master.jpg',
        mdsvex: 'airplane',
        icons: ['c++', 'arduino'],
    },
]